name: FoD Test

on: 
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  job: 
    name: FODUploader
    runs-on: ubuntu-latest
    steps:
   # - uses: actions/FoD-SAST-Upload
    - uses: ./.github/workflows
 
